"""fix: conflict in timezone between python and postgresql

Revision ID: 2f97a8a9059f
Revises: 91ba2cfd2289
Create Date: 2026-06-22 15:13:38.626638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = '2f97a8a9059f'
down_revision: Union[str, Sequence[str], None] = '91ba2cfd2289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
