"""feature add: added some validation fields defaults and tried to optimize and correct the table

Revision ID: 91ba2cfd2289
Revises: 8b539c76a044
Create Date: 2026-06-21 18:54:20.604662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ba2cfd2289'
down_revision: Union[str, Sequence[str], None] = '8b539c76a044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='genderenum'),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='genderenum'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
